"""roles

Revision ID: 2037dc4939c9
Revises: 9a80f38a6b07
Create Date: 2017-02-06 15:15:48.012000

"""

# revision identifiers, used by Alembic.
revision = '2037dc4939c9'
down_revision = '9a80f38a6b07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permission', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permission')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
