"""confirmation

Revision ID: 6054bb4e6514
Revises: None
Create Date: 2017-02-04 15:14:11.936000

"""

# revision identifiers, used by Alembic.
revision = '6054bb4e6514'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
