"""add post click nums

Revision ID: 99a94ea1fe9a
Revises: 046c8215011f
Create Date: 2017-02-14 15:12:23.208000

"""

# revision identifiers, used by Alembic.
revision = '99a94ea1fe9a'
down_revision = '046c8215011f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('clicknum', sa.Integer(), nullable=True))
    # op.drop_column('posts', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('posts', sa.Column('test', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('posts', 'clicknum')
    ### end Alembic commands ###
