"""add post title

Revision ID: dbcb56baa797
Revises: fbb0d853bb39
Create Date: 2017-02-10 12:00:10.897000

"""

# revision identifiers, used by Alembic.
revision = 'dbcb56baa797'
down_revision = 'fbb0d853bb39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'tags')
    ### end Alembic commands ###
